### ISSUE TITLE
Issue after npm install, ng serve does not work

### ISSUE THREAD

**Issue by webdevsoup** [creativetimofficial/light-bootstrap-dashboard-pro-angular#11]
I just purchased this, and am having issues.  Here are my errors I get during ng serve:

`@angular/compiler-cli@4.4.3 requires typescript@'>=2.1.0 <2.4.0' but 2.5.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.1.0 <2.4.0'

To disable this warning run "ng set --global warnings.typescriptMismatch=false".

ERROR in Error: NouisliderModule is not an NgModule
    at _getNgModuleMetadata (/Users/adamcampbell/Documents/Development/appDir/nwfmember/node_modules/@angular/compiler-cli/src/ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (/Users/adamcampbell/Documents/Development/appDir/nwfmember/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /Users/adamcampbell/Documents/Development/appDir/nwfmember/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/Users/adamcampbell/Documents/Development/appDir/nwfmember/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at includeLazyRouteAndSubRoutes (/Users/adamcampbell/Documents/Development/appDir/nwfmember/node_modules/@angular/compiler-cli/src/ngtools_impl.js:66:25)
    at Array.reduce (native)
    at Object.listLazyRoutesOfModule (/Users/adamcampbell/Documents/Development/appDir/nwfmember/node_modules/@angular/compiler-cli/src/ngtools_impl.js:54:36)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/adamcampbell/Documents/Development/appDir/nwfmember/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/adamcampbell/Documents/Development/appDir/nwfmember/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/adamcampbell/Documents/Development/appDir/nwfmember/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

I followed the first instruction, running install of typescript, and I get this:

`lbd-pro-angular@1.2.0 /Users/adamcampbell/Documents/Development/appDir/nwfmember
└── typescript@2.3.4  invalid
`

Help, please?

**Comment by webdevsoup** [comment]
Ok, I I did update the typescript after reinstalling npm and node on my Mac.  To fix the issue with NouisliderModule, I did the following:

go in `src/app/forms/forms.module.ts` and replace line 9 with: import {NouisliderModule} from 'ng2-nouislider/src/nouislider';

**Comment by alexandru-paduraru** [comment]
@webdevsoup we just did an update with this fix. Thank you so much for your support!
